<?php

return [
    'auto_publish' => env('AI_NEWS_AUTO_PUBLISH', false),
    'min_quality_score' => env('AI_NEWS_MIN_QUALITY_SCORE', 70),
    'max_articles_per_hour' => env('AI_NEWS_MAX_ARTICLES_PER_HOUR', 12),
    'sanitize_prompt_version' => env('AI_NEWS_SANITIZE_PROMPT_VERSION', 'v1'),
    'schedule_every_minutes' => env('AI_NEWS_SCHEDULE_EVERY_MINUTES', 60),
    'max_items_per_source' => env('AI_NEWS_MAX_ITEMS_PER_SOURCE', 10),
    'deduplication' => [
        'enabled' => env('AI_NEWS_DEDUP_ENABLED', true),
        'similarity_threshold' => env('AI_NEWS_DEDUP_SIMILARITY_THRESHOLD', 0.72),
        'lookback_days' => env('AI_NEWS_DEDUP_LOOKBACK_DAYS', 14),
        'candidate_limit' => env('AI_NEWS_DEDUP_CANDIDATE_LIMIT', 80),
    ],
    'scope' => [
        'store_rejected' => env('AI_NEWS_SCOPE_STORE_REJECTED', false),
        'trusted_domains' => [
            'bbc.co.uk',
            'bbc.com',
            'theguardian.com',
            'aljazeera.com',
            'reuters.com',
            'feeds.reuters.com',
            'apnews.com',
            'news.un.org',
            'foreignaffairs.com',
            'thediplomat.com',
            'warontherocks.com',
            'geopoliticalfutures.com',
            'cfr.org',
        ],
        'allow_keywords' => [
            'geopolitica', 'geopolitical', 'geopolitics',
            'world', 'politics', 'international', 'foreign policy',
            'state department', 'white house', 'kremlin', 'pentagon',
            'guerra', 'war', 'conflict', 'conflicts',
            'nato', 'onu', 'united nations', 'un security council',
            'ue', 'eu', 'european union',
            'sanzioni', 'sanctions', 'embargo',
            'ministero degli esteri', 'foreign minister', 'diplomacy', 'diplomatic',
            'summit', 'peace talks', 'ceasefire', 'arms', 'military',
            'russia', 'ukraine', 'china', 'taiwan', 'middle east', 'gaza', 'israel', 'iran',
            'election', 'elections', 'president', 'prime minister', 'parliament',
            'intelligence', 'cyberwar', 'security policy',
            'border', 'migration policy', 'refugees',
            'oil', 'gas supply', 'energy security',
        ],
        'block_keywords' => [
            'serie a', 'champions league', 'premier league', 'nba', 'nfl',
            'tennis', 'formula 1', 'motogp', 'goal', 'match', 'transfer market',
            'calcio', 'basket', 'volley', 'atletica', 'olimpiadi', 'olympics',
            'gossip', 'celebrity', 'entertainment', 'movie', 'music',
            'fashion', 'beauty', 'lifestyle', 'recipe', 'travel',
        ],
    ],
    'queues' => [
        'ingest' => env('AI_NEWS_QUEUE_INGEST', 'news-ingest'),
        'ingest_receive' => env('AI_NEWS_QUEUE_INGEST_RECEIVE', 'news-ingest'),
        'extract' => env('AI_NEWS_QUEUE_EXTRACT', 'news-extract'),
        'sanitize' => env('AI_NEWS_QUEUE_SANITIZE', 'news-sanitize'),
        'publish' => env('AI_NEWS_QUEUE_PUBLISH', 'news-publish'),
        'images' => env('AI_NEWS_QUEUE_IMAGES', 'news-images'),
    ],
    'ingest' => [
        'token' => env('AI_NEWS_INGEST_TOKEN', ''),
    ],
    'ai' => [
        'enabled' => env('AI_NEWS_AI_ENABLED', false),
        'provider' => env('AI_NEWS_AI_PROVIDER', 'ollama'),
        'base_url' => env('AI_NEWS_AI_BASE_URL', 'http://127.0.0.1:11434'),
        'api_key' => env('AI_NEWS_AI_API_KEY'),
        'model' => env('AI_NEWS_AI_MODEL', 'llama3.1'),
        'temperature' => env('AI_NEWS_AI_TEMPERATURE', 0.4),
        'timeout_seconds' => env('AI_NEWS_AI_TIMEOUT_SECONDS', 30),
    ],
    'crewai' => [
        'enabled' => env('AI_NEWS_CREWAI_ENABLED', false),
        'base_url' => env('AI_NEWS_CREWAI_BASE_URL', 'http://127.0.0.1:8001'),
        'endpoint' => env('AI_NEWS_CREWAI_ENDPOINT', '/process'),
        'timeout_seconds' => env('AI_NEWS_CREWAI_TIMEOUT_SECONDS', 120),
        'api_key' => env('AI_NEWS_CREWAI_API_KEY'),
    ],
    'images' => [
        'enabled' => env('AI_NEWS_IMAGES_ENABLED', false),
        'provider' => env('AI_NEWS_IMAGES_PROVIDER', 'gemini'),
        'base_url' => env('AI_NEWS_IMAGES_BASE_URL', 'https://generativelanguage.googleapis.com'),
        'api_key' => env('AI_NEWS_IMAGES_API_KEY'),
        'model' => env('AI_NEWS_IMAGES_MODEL', 'gemini-2.5-flash-image'),
        'timeout_seconds' => env('AI_NEWS_IMAGES_TIMEOUT_SECONDS', 60),
        'retry_attempts' => env('AI_NEWS_IMAGES_RETRY_ATTEMPTS', 1),
        'retry_sleep_ms' => env('AI_NEWS_IMAGES_RETRY_SLEEP_MS', 1500),
        'style' => env('AI_NEWS_IMAGES_STYLE', 'editoriale realistico, geopolitica, nessun logo o testo leggibile'),
    ],
];
