<?php

return [
    /*
    | Regioni mappabili: alias (match su region_name + contesto articolo) → coordinate.
    | Ordine irrilevante: il resolver sceglie l'alias più lungo che combacia.
    */
    'regions' => [
        ['label' => 'Russia e Ucraina', 'aliases' => ['russia ukraine', 'ucraina russia', 'donbas', 'crimea', 'ucraina e russia', 'russia e ucraina'], 'lat' => 48.5, 'long' => 37.5],
        ['label' => 'Gaza e Israele', 'aliases' => ['gaza strip', 'striscia di gaza', 'gaza israel', 'israel gaza', 'israele gaza', 'gaza e israele', 'israele e gaza', 'israelo-palestinese', 'israelo palestinese'], 'lat' => 31.5, 'long' => 34.45],
        ['label' => 'Israele e Libano', 'aliases' => ['israel lebanon', 'israele libano', 'libano israele', 'lebanon israel', 'israele e libano', 'libano e israele', 'hezbollah', 'hezbolla', 'hizbullah'], 'lat' => 33.3, 'long' => 35.3],
        ['label' => 'Mar Rosso', 'aliases' => ['red sea', 'mar rosso', 'houthi', 'huthi', 'yemen red sea', 'yemenita', 'yemeniti', 'bab el-mandeb', 'bab el mandeb'], 'lat' => 15.5, 'long' => 42.5],
        ['label' => 'Stretto di Taiwan', 'aliases' => ['taiwan strait', 'stretto di taiwan', 'taiwanese', 'taiwanesi'], 'lat' => 24.0, 'long' => 119.5],
        ['label' => 'Mar Cinese Meridionale', 'aliases' => ['south china sea', 'mar cinese meridionale', 'mare cinese meridionale', 'mar cinese', 'mare della cina meridionale', 'mar del sud cina', 'paracel', 'spratly'], 'lat' => 12.0, 'long' => 114.0],
        ['label' => 'Indo-Pacifico', 'aliases' => ['indo pacific', 'indo-pacific', 'indo pacifico'], 'lat' => 5.0, 'long' => 115.0],
        ['label' => 'Corno d\'Africa', 'aliases' => ['horn of africa', 'corno d africa', 'corno dell africa', 'corno d\'africa'], 'lat' => 9.0, 'long' => 45.0],
        ['label' => 'Balcani Occidentali', 'aliases' => ['western balkans', 'balcani occidentali', 'balcani', 'balcanico', 'balcanica', 'balcanici', 'balcaniche'], 'lat' => 43.5, 'long' => 20.5],
        ['label' => 'Medio Oriente', 'aliases' => ['middle east', 'medio oriente', 'levant', 'levante', 'mediorientale', 'medio-orientale', 'mediorientali'], 'lat' => 33.0, 'long' => 44.0],
        ['label' => 'Stati Uniti', 'aliases' => ['united states', 'stati uniti', 'usa', 'u.s.', 'washington', 'pentagon', 'white house', 'u.s.a.', 'pentagono', 'casa bianca', 'statunitense', 'statunitensi', 'americano', 'americana', 'americani', 'americane'], 'lat' => 38.9072, 'long' => -77.0369],
        ['label' => 'Regno Unito', 'aliases' => ['united kingdom', 'regno unito', 'london', 'londra', 'britain', 'uk', 'u.k.', 'britannico', 'britannica', 'britannici', 'britanniche', 'inglese', 'inglesi'], 'lat' => 51.5074, 'long' => -0.1278],
        ['label' => 'Francia', 'aliases' => ['france', 'francia', 'paris', 'parigi', 'francese', 'francesi'], 'lat' => 48.8566, 'long' => 2.3522],
        ['label' => 'Germania', 'aliases' => ['germany', 'germania', 'berlin', 'berlino', 'tedesco', 'tedesca', 'tedeschi', 'tedesche'], 'lat' => 52.52, 'long' => 13.405],
        ['label' => 'Polonia', 'aliases' => ['poland', 'polonia', 'warsaw', 'varsavia', 'polacco', 'polacca', 'polacchi', 'polacche'], 'lat' => 52.2297, 'long' => 21.0122],
        ['label' => 'Unione Europea', 'aliases' => ['european union', 'unione europea', 'bruxelles', 'brussels', 'europa', 'ue', 'u.e.', 'europeo', 'europea', 'europei', 'europee'], 'lat' => 50.8503, 'long' => 4.3517],
        ['label' => 'Mediterraneo', 'aliases' => ['mediterranean', 'mediterraneo', 'mediterranea', 'mediterranee', 'mediterranei'], 'lat' => 35.0, 'long' => 18.0],
        ['label' => 'Sahel', 'aliases' => ['sahel'], 'lat' => 17.5707, 'long' => 3.9962],
        ['label' => 'Sudan', 'aliases' => ['sudan', 'khartoum', 'sudanese', 'sudanesi'], 'lat' => 15.5007, 'long' => 32.5599],
        ['label' => 'Etiopia', 'aliases' => ['ethiopia', 'etiopia', 'addis ababa', 'etiope', 'etiopici', 'etiopico', 'etiopica'], 'lat' => 9.032, 'long' => 38.7469],
        ['label' => 'Nigeria', 'aliases' => ['nigeria', 'lagos', 'abuja', 'nigeriano', 'nigeriana', 'nigeriani', 'nigeriane'], 'lat' => 9.0765, 'long' => 7.3986],
        ['label' => 'Africa Subsahariana', 'aliases' => ['africa subsahariana', 'sub saharan africa', 'africa'], 'lat' => 9.082, 'long' => 8.6753],
        ['label' => 'Libia', 'aliases' => ['libya', 'libia', 'tripoli', 'libico', 'libica', 'libici', 'libiche'], 'lat' => 32.8872, 'long' => 13.1913],
        ['label' => 'Algeria', 'aliases' => ['algeria', 'algeri', 'algerino', 'algerina', 'algerini', 'algerine'], 'lat' => 36.7538, 'long' => 3.0588],
        ['label' => 'Egitto', 'aliases' => ['egypt', 'egitto', 'cairo', 'il cairo', 'egiziano', 'egiziana', 'egiziani', 'egiziane', 'egizio', 'egizia'], 'lat' => 30.0444, 'long' => 31.2357],
        ['label' => 'Siria', 'aliases' => ['syria', 'siria', 'damascus', 'damasco', 'siriano', 'siriana', 'siriani', 'siriane'], 'lat' => 33.5138, 'long' => 36.2765],
        ['label' => 'Iraq', 'aliases' => ['iraq', 'baghdad', 'bagdad', 'irak', 'iracheno', 'irachena', 'iracheni', 'irachene'], 'lat' => 33.3152, 'long' => 44.3661],
        ['label' => 'Afghanistan', 'aliases' => ['afghanistan', 'kabul', 'afghano', 'afghana', 'afghani', 'afghane', 'talebano', 'talebani'], 'lat' => 34.5553, 'long' => 69.2075],
        ['label' => 'Pakistan', 'aliases' => ['pakistan', 'islamabad', 'pakistano', 'pakistana', 'pakistani', 'pakistane'], 'lat' => 33.6844, 'long' => 73.0479],
        ['label' => 'India', 'aliases' => ['india', 'new delhi', 'nuova delhi', 'indiano', 'indiana', 'indiani', 'indiane'], 'lat' => 28.6139, 'long' => 77.209],
        ['label' => 'Giappone', 'aliases' => ['japan', 'giappone', 'tokyo', 'tokio', 'giapponese', 'giapponesi'], 'lat' => 35.6762, 'long' => 139.6503],
        ['label' => 'Corea del Nord', 'aliases' => ['north korea', 'corea del nord', 'pyongyang', 'nordcoreano', 'nordcoreana', 'nordcoreani', 'nordcoreane'], 'lat' => 39.0392, 'long' => 125.7625],
        ['label' => 'Corea del Sud', 'aliases' => ['south korea', 'corea del sud', 'seoul', 'seul', 'sudcoreano', 'sudcoreana', 'sudcoreani', 'sudcoreane'], 'lat' => 37.5665, 'long' => 126.978],
        ['label' => 'Taiwan', 'aliases' => ['taiwan', 'taipei', 'taiwanese', 'taiwanesi'], 'lat' => 25.033, 'long' => 121.5654],
        ['label' => 'Cina', 'aliases' => ['china', 'cina', 'beijing', 'pechino', 'cinese', 'cinesi'], 'lat' => 39.9042, 'long' => 116.4074],
        ['label' => 'Hong Kong', 'aliases' => ['hong kong'], 'lat' => 22.3193, 'long' => 114.1694],
        ['label' => 'Ucraina', 'aliases' => ['ukraine', 'ucraina', 'kyiv', 'kiev', 'ucraino', 'ucraini', 'ucraine'], 'lat' => 50.4501, 'long' => 30.5234],
        ['label' => 'Bielorussia', 'aliases' => ['belarus', 'bielorussia', 'minsk', 'bielorusso', 'bielorussa', 'bielorussi', 'bielorusse'], 'lat' => 53.9006, 'long' => 27.559],
        ['label' => 'Russia', 'aliases' => ['russia', 'russian federation', 'moscow', 'mosca', 'russo', 'russa', 'russi', 'russe'], 'lat' => 55.7558, 'long' => 37.6173],
        ['label' => 'Israele', 'aliases' => ['israel', 'israele', 'jerusalem', 'gerusalemme', 'tel aviv', 'israeliano', 'israeliana', 'israeliani', 'israeliane'], 'lat' => 31.7683, 'long' => 35.2137],
        ['label' => 'Palestina', 'aliases' => ['palestine', 'palestina', 'west bank', 'cisgiordania', 'palestinese', 'palestinesi'], 'lat' => 31.95, 'long' => 35.2],
        ['label' => 'Gaza', 'aliases' => ['gaza'], 'lat' => 31.5017, 'long' => 34.4668],
        ['label' => 'Libano', 'aliases' => ['lebanon', 'libano', 'beirut', 'libanese', 'libanesi'], 'lat' => 33.8938, 'long' => 35.5018],
        ['label' => 'Iran', 'aliases' => ['iran', 'tehran', 'teheran', 'iraniano', 'iraniana', 'iraniani', 'iraniane', 'teocratico', 'teocrazia'], 'lat' => 35.6892, 'long' => 51.389],
        ['label' => 'Arabia Saudita', 'aliases' => ['saudi arabia', 'arabia saudita', 'riyadh', 'riyad', 'saudita', 'saudite', 'sauditi'], 'lat' => 24.7136, 'long' => 46.6753],
        ['label' => 'Yemen', 'aliases' => ['yemen', 'sanaa', 'sana', 'yemenita', 'yemenite', 'yemeniti'], 'lat' => 15.3694, 'long' => 44.191],
        ['label' => 'Turchia', 'aliases' => ['turkey', 'turchia', 'turca', 'turco', 'turchese', 'ankara', 'istanbul', 'turchi', 'turche'], 'lat' => 39.9334, 'long' => 32.8597],
        ['label' => 'Armenia', 'aliases' => ['armenia', 'yerevan', 'armeno', 'armena', 'armeni', 'armene'], 'lat' => 40.1792, 'long' => 44.4991],
        ['label' => 'Azerbaigian', 'aliases' => ['azerbaijan', 'azerbaigian', 'baku', 'azero', 'azera', 'azeri', 'azere', 'azerbaigiano', 'azerbaigiana', 'azerbaigiani', 'azerbaigiane'], 'lat' => 40.4093, 'long' => 49.8671],
        ['label' => 'Georgia', 'aliases' => ['georgia', 'tbilisi', 'georgiano', 'georgiana', 'georgiani', 'georgiane'], 'lat' => 41.7151, 'long' => 44.8271],
        ['label' => 'Venezuela', 'aliases' => ['venezuela', 'caracas', 'venezuelano', 'venezuelana', 'venezuelani', 'venezuelane'], 'lat' => 10.4806, 'long' => -66.9036],
        ['label' => 'Cuba', 'aliases' => ['cuba', 'havana', 'l avana', 'cubano', 'cubana', 'cubani', 'cubane'], 'lat' => 23.1136, 'long' => -82.3666],
        ['label' => 'Messico', 'aliases' => ['mexico', 'messico', 'mexico city', 'messicano', 'messicana', 'messicani', 'messicane'], 'lat' => 19.4326, 'long' => -99.1332],
        ['label' => 'Brasile', 'aliases' => ['brazil', 'brasile', 'brasilia', 'brasiliano', 'brasiliana', 'brasiliani', 'brasiliane'], 'lat' => -15.7939, 'long' => -47.8828],
        ['label' => 'Argentina', 'aliases' => ['argentina', 'buenos aires', 'argentino', 'argentina', 'argentini', 'argentine'], 'lat' => -34.6037, 'long' => -58.3816],
        ['label' => 'NATO', 'aliases' => ['nato', 'atlantic'], 'lat' => 50.8503, 'long' => 4.3517],
        ['label' => 'Asia', 'aliases' => ['asia'], 'lat' => 34.0479, 'long' => 100.6197],
        ['label' => 'Italia', 'aliases' => ['italia', 'roma', 'italiano', 'italiana', 'italiani', 'italiane'], 'lat' => 41.9028, 'long' => 12.4964],
        ['label' => 'Spagna', 'aliases' => ['spagna', 'spain', 'madrid', 'spagnolo', 'spagnola', 'spagnoli', 'spagnole'], 'lat' => 40.4168, 'long' => -3.7038],
        ['label' => 'Grecia', 'aliases' => ['grecia', 'greece', 'atene', 'athens', 'greco', 'greca', 'greci', 'greche'], 'lat' => 37.9838, 'long' => 23.7275],
        ['label' => 'Belgio', 'aliases' => ['belgio', 'belgium', 'belga', 'belgi'], 'lat' => 50.8503, 'long' => 4.3517],
        ['label' => 'Paesi Bassi', 'aliases' => ['paesi bassi', 'netherlands', 'olanda', 'amsterdam', 'olandese', 'olandesi'], 'lat' => 52.3676, 'long' => 4.9041],
        ['label' => 'Svizzera', 'aliases' => ['svizzera', 'switzerland', 'berna', 'bern', 'svizzero', 'svizzera', 'svizzeri', 'svizzere'], 'lat' => 46.9480, 'long' => 7.4474],
        ['label' => 'Austria', 'aliases' => ['austria', 'vienna', 'austriaco', 'austriaca', 'austriaci', 'austriache'], 'lat' => 48.2082, 'long' => 16.3738],
        ['label' => 'Svezia', 'aliases' => ['svezia', 'sweden', 'stoccolma', 'stockholm', 'svedese', 'svedesi'], 'lat' => 59.3293, 'long' => 18.0686],
        ['label' => 'Norvegia', 'aliases' => ['norvegia', 'norway', 'oslo', 'norvegese', 'norvegesi'], 'lat' => 59.9139, 'long' => 10.7522],
        ['label' => 'Finlandia', 'aliases' => ['finlandia', 'finland', 'helsinki', 'finlandese', 'finlandesi'], 'lat' => 60.1699, 'long' => 24.9384],
        ['label' => 'Danimarca', 'aliases' => ['danimarca', 'denmark', 'copenaghen', 'copenhagen', 'danese', 'danesi'], 'lat' => 55.6761, 'long' => 12.5683],
        ['label' => 'Irlanda', 'aliases' => ['irlanda', 'ireland', 'dublino', 'dublin', 'irlandese', 'irlandesi'], 'lat' => 53.3498, 'long' => -6.2603],
        ['label' => 'Portogallo', 'aliases' => ['portogallo', 'portugal', 'lisbona', 'lisbon', 'portoghese', 'portoghesi'], 'lat' => 38.7223, 'long' => -9.1393],
        ['label' => 'Serbia', 'aliases' => ['serbia', 'belgrado', 'belgrade', 'serbo', 'serba', 'serbi', 'serbe'], 'lat' => 44.7866, 'long' => 20.4489],
        ['label' => 'Kosovo', 'aliases' => ['kosovo', 'pristina', 'kosovaro', 'kosovara', 'kosovari', 'kosovare'], 'lat' => 42.6629, 'long' => 21.1655],
        ['label' => 'Bosnia ed Erzegovina', 'aliases' => ['bosnia', 'erzegovina', 'sarajevo', 'bosniaco', 'bosniaca', 'bosniaci', 'bosniache'], 'lat' => 43.8563, 'long' => 18.4131],
        ['label' => 'Croazia', 'aliases' => ['croazia', 'croatia', 'zagabria', 'zagreb', 'croato', 'croata', 'croati', 'croate'], 'lat' => 45.8150, 'long' => 15.9819],
        ['label' => 'Albania', 'aliases' => ['albania', 'tirana', 'albanese', 'albanesi'], 'lat' => 41.3275, 'long' => 19.8187],
        ['label' => 'Montenegro', 'aliases' => ['montenegro', 'podgorica', 'montenegrino', 'montenegrina', 'montenegrini', 'montenegrine'], 'lat' => 42.4413, 'long' => 19.2636],
        ['label' => 'Macedonia del Nord', 'aliases' => ['macedonia del nord', 'north macedonia', 'skopje', 'macedone', 'macedoni'], 'lat' => 41.9981, 'long' => 21.4254],
        ['label' => 'Bulgaria', 'aliases' => ['bulgaria', 'sofia', 'bulgaro', 'bulgara', 'bulgari', 'bulgare'], 'lat' => 42.6977, 'long' => 23.3219],
        ['label' => 'Romania', 'aliases' => ['romania', 'bucarest', 'bucharest', 'rumeno', 'rumena', 'rumeni', 'rumene'], 'lat' => 44.4268, 'long' => 26.1025],
        ['label' => 'Moldavia', 'aliases' => ['moldavia', 'moldova', 'chisinau', 'moldavo', 'moldava', 'moldavi', 'moldave'], 'lat' => 47.0105, 'long' => 28.8638],
        ['label' => 'Cipro', 'aliases' => ['cipro', 'cyprus', 'nicosia', 'cipriota', 'ciprioti'], 'lat' => 35.1856, 'long' => 33.3823],
        ['label' => 'Estonia', 'aliases' => ['estonia', 'tallinn', 'estone', 'estoni'], 'lat' => 59.4370, 'long' => 24.7536],
        ['label' => 'Lettonia', 'aliases' => ['lettonia', 'latvia', 'riga', 'lettone', 'lettoni'], 'lat' => 56.9496, 'long' => 24.1052],
        ['label' => 'Lituania', 'aliases' => ['lituania', 'lithuania', 'vilnius', 'lituano', 'lituana', 'lituani', 'lituane'], 'lat' => 54.6872, 'long' => 25.2797],
        ['label' => 'Qatar', 'aliases' => ['qatar', 'doha', 'qatariota', 'qatarioti'], 'lat' => 25.2854, 'long' => 51.5310],
        ['label' => 'Emirati Arabi Uniti', 'aliases' => ['emirati arabi', 'eau', 'uae', 'dubai', 'abu dhabi', 'emiratino', 'emiratini'], 'lat' => 24.4539, 'long' => 54.3773],
        ['label' => 'Giordania', 'aliases' => ['giordania', 'jordan', 'amman', 'giordano', 'giordana', 'giordani', 'giordane'], 'lat' => 31.9454, 'long' => 35.9284],
        ['label' => 'Kuwait', 'aliases' => ['kuwait', 'kuwait city', 'kuwaitiano', 'kuwaitiana', 'kuwaitiani', 'kuwaitiane'], 'lat' => 29.3759, 'long' => 47.9774],
        ['label' => 'Bahrain', 'aliases' => ['bahrain', 'manama'], 'lat' => 26.2285, 'long' => 50.5860],
        ['label' => 'Oman', 'aliases' => ['oman', 'muscat', 'omanita', 'omaniti'], 'lat' => 23.5859, 'long' => 58.4059],
        ['label' => 'Marocco', 'aliases' => ['marocco', 'morocco', 'rabat', 'marocchino', 'marocchina', 'marocchini', 'marocchine'], 'lat' => 34.0209, 'long' => -6.8416],
        ['label' => 'Tunisia', 'aliases' => ['tunisia', 'tunisi', 'tunisino', 'tunisina', 'tunisini', 'tunisine'], 'lat' => 36.8065, 'long' => 10.1815],
        ['label' => 'Somalia', 'aliases' => ['somalia', 'mogadiscio', 'mogadishu', 'somalo', 'somala', 'somali', 'somale'], 'lat' => 2.0469, 'long' => 45.3182],
        ['label' => 'Mali', 'aliases' => ['mali', 'bamako', 'maliano', 'maliana', 'maliani', 'maliane'], 'lat' => 12.6392, 'long' => -8.0029],
        ['label' => 'Niger', 'aliases' => ['niger', 'niamey', 'nigerino', 'nigerina', 'nigerini', 'nigerine'], 'lat' => 13.5116, 'long' => 2.1254],
        ['label' => 'Ciad', 'aliases' => ['chad', 'ciad', 'n djamena', 'ciadiano', 'ciadiana', 'ciadiani', 'ciadiane'], 'lat' => 12.1348, 'long' => 15.0557],
        ['label' => 'Burkina Faso', 'aliases' => ['burkina faso', 'ouagadougou', 'burkinabe', 'burkinabi'], 'lat' => 12.3714, 'long' => -1.5197],
        ['label' => 'Repubblica Democratica del Congo', 'aliases' => ['congo', 'rdc', 'drc', 'kinshasa', 'congolese', 'congolesi'], 'lat' => -4.4419, 'long' => 15.2663],
        ['label' => 'Kenya', 'aliases' => ['kenya', 'nairobi', 'keniota', 'kenioti'], 'lat' => -1.2921, 'long' => 36.8219],
        ['label' => 'Sudafrica', 'aliases' => ['sudafrica', 'south africa', 'pretoria', 'citta del capo', 'cape town', 'sudafricano', 'sudafricana', 'sudafricani', 'sudafricane'], 'lat' => -25.7479, 'long' => 28.2293],
        ['label' => 'Australia', 'aliases' => ['australia', 'canberra', 'sydney', 'australiano', 'australiana', 'australiani', 'australiane'], 'lat' => -35.2809, 'long' => 149.1300],
        ['label' => 'Nuova Zelanda', 'aliases' => ['nuova zelanda', 'new zealand', 'wellington', 'neozelandese', 'neozelandesi'], 'lat' => -41.2865, 'long' => 174.7762],
        ['label' => 'Indonesia', 'aliases' => ['indonesia', 'giacarta', 'jakarta', 'indonesiano', 'indonesiana', 'indonesiani', 'indonesiane'], 'lat' => -6.2088, 'long' => 106.8456],
        ['label' => 'Filippine', 'aliases' => ['filippine', 'philippines', 'manila', 'filippino', 'filippina', 'filippini', 'filippine'], 'lat' => 14.5995, 'long' => 120.9842],
        ['label' => 'Vietnam', 'aliases' => ['vietnam', 'hanoi', 'vietnamita', 'vietnamiti'], 'lat' => 21.0285, 'long' => 105.8542],
        ['label' => 'Thailandia', 'aliases' => ['thailandia', 'thailand', 'bangkok', 'thailandese', 'thailandesi'], 'lat' => 13.7563, 'long' => 100.5018],
        ['label' => 'Malaysia', 'aliases' => ['malaysia', 'malesia', 'kuala lumpur', 'malese', 'malesi', 'malaysiano', 'malaysiani'], 'lat' => 3.1390, 'long' => 101.6869],
        ['label' => 'Singapore', 'aliases' => ['singapore', 'singaporiano', 'singaporiani'], 'lat' => 1.3521, 'long' => 103.8198],
        ['label' => 'Myanmar', 'aliases' => ['myanmar', 'birmania', 'burma', 'naypyidaw', 'birmano', 'birmana', 'birmani', 'birmane'], 'lat' => 19.7633, 'long' => 96.0785],
        ['label' => 'Bangladesh', 'aliases' => ['bangladesh', 'dacca', 'dhaka', 'bangladese', 'bangladesi'], 'lat' => 23.8103, 'long' => 90.4125],
        ['label' => 'Sri Lanka', 'aliases' => ['sri lanka', 'colombo'], 'lat' => 6.9271, 'long' => 79.8612],
        ['label' => 'Nepal', 'aliases' => ['nepal', 'kathmandu', 'nepalese', 'nepalesi'], 'lat' => 27.7172, 'long' => 85.3240],
        ['label' => 'Kazakistan', 'aliases' => ['kazakhstan', 'kazakistan', 'astana', 'kazako', 'kazaka', 'kazaki', 'kazake'], 'lat' => 51.1605, 'long' => 71.4704],
        ['label' => 'Uzbekistan', 'aliases' => ['uzbekistan', 'uzbekistan', 'tashkent', 'uzbeko', 'uzbeka', 'uzbeki', 'uzbeke'], 'lat' => 41.2995, 'long' => 69.2401],
        ['label' => 'Canada', 'aliases' => ['canada', 'ottawa', 'toronto', 'canadese', 'canadesi'], 'lat' => 45.4215, 'long' => -75.6972],
        ['label' => 'Colombia', 'aliases' => ['colombia', 'bogota', 'colombiano', 'colombiana', 'colombiani', 'colombiane'], 'lat' => 4.7110, 'long' => -74.0721],
        ['label' => 'Cile', 'aliases' => ['cile', 'chile', 'santiago', 'cileno', 'cilena', 'cileni', 'cilene'], 'lat' => -33.4489, 'long' => -70.6693],
        ['label' => 'Perù', 'aliases' => ['peru', 'lima', 'peruviano', 'peruviana', 'peruviani', 'peruviane'], 'lat' => -12.0464, 'long' => -77.0428],
        ['label' => 'Ecuador', 'aliases' => ['ecuador', 'quito', 'ecuadoriano', 'ecuadoriana', 'ecuadoriani', 'ecuadoriane'], 'lat' => -0.1807, 'long' => -78.4678],
        ['label' => 'Bolivia', 'aliases' => ['bolivia', 'la paz', 'boliviano', 'boliviana', 'boliviani', 'boliviane'], 'lat' => -16.4897, 'long' => -68.1193],
        ['label' => 'Paraguay', 'aliases' => ['paraguay', 'asuncion', 'paraguaiano', 'paraguayana', 'paraguaiani', 'paraguaiane'], 'lat' => -25.2637, 'long' => -57.5759],
        ['label' => 'Uruguay', 'aliases' => ['uruguay', 'montevideo', 'uruguaiano', 'uruguaiana', 'uruguaiani', 'uruguaiane'], 'lat' => -34.9011, 'long' => -56.1645],
        ['label' => 'Panama', 'aliases' => ['panama', 'panamense', 'panamensi'], 'lat' => 8.9824, 'long' => -79.5199],
    ],

    'generic_region_patterns' => [
        'area non specificata',
        'non specificata',
        'non specificato',
        'globale',
        'global',
        'worldwide',
        'mondiale',
        'internazionale generale',
        'unknown region',
        'regione sconosciuta',
    ],
];
