<?php

return [
    /*
    | Regioni mappabili: alias (match su region_name + contesto articolo) → coordinate.
    | Ordine irrilevante: il resolver sceglie l'alias più lungo che combacia.
    */
    'regions' => [
        ['label' => 'Russia e Ucraina', 'aliases' => ['russia ukraine', 'ucraina russia', 'donbas', 'crimea', 'crimea'], 'lat' => 48.5, 'long' => 37.5],
        ['label' => 'Gaza e Israele', 'aliases' => ['gaza strip', 'striscia di gaza', 'gaza israel', 'israel gaza', 'israele gaza'], 'lat' => 31.5, 'long' => 34.45],
        ['label' => 'Israele e Libano', 'aliases' => ['israel lebanon', 'israele libano', 'libano israele', 'lebanon israel'], 'lat' => 33.3, 'long' => 35.3],
        ['label' => 'Mar Rosso', 'aliases' => ['red sea', 'mar rosso', 'houthi', 'huthi', 'yemen red sea'], 'lat' => 15.5, 'long' => 42.5],
        ['label' => 'Stretto di Taiwan', 'aliases' => ['taiwan strait', 'stretto di taiwan'], 'lat' => 24.0, 'long' => 119.5],
        ['label' => 'Mar Cinese Meridionale', 'aliases' => ['south china sea', 'mar cinese meridionale', 'mar del sud cina'], 'lat' => 12.0, 'long' => 114.0],
        ['label' => 'Indo-Pacifico', 'aliases' => ['indo pacific', 'indo-pacific', 'indo pacifico'], 'lat' => 5.0, 'long' => 115.0],
        ['label' => 'Corno d\'Africa', 'aliases' => ['horn of africa', 'corno d africa', 'corno dell africa'], 'lat' => 9.0, 'long' => 45.0],
        ['label' => 'Balcani Occidentali', 'aliases' => ['western balkans', 'balcani occidentali', 'balcani'], 'lat' => 43.5, 'long' => 20.5],
        ['label' => 'Medio Oriente', 'aliases' => ['middle east', 'medio oriente', 'levant', 'levante'], 'lat' => 33.0, 'long' => 44.0],
        ['label' => 'Stati Uniti', 'aliases' => ['united states', 'stati uniti', 'usa', 'u.s.', 'washington', 'pentagon', 'white house'], 'lat' => 38.9072, 'long' => -77.0369],
        ['label' => 'Regno Unito', 'aliases' => ['united kingdom', 'regno unito', 'london', 'londra', 'britain'], 'lat' => 51.5074, 'long' => -0.1278],
        ['label' => 'Francia', 'aliases' => ['france', 'francia', 'paris', 'parigi'], 'lat' => 48.8566, 'long' => 2.3522],
        ['label' => 'Germania', 'aliases' => ['germany', 'germania', 'berlin', 'berlino'], 'lat' => 52.52, 'long' => 13.405],
        ['label' => 'Polonia', 'aliases' => ['poland', 'polonia', 'warsaw', 'varsavia'], 'lat' => 52.2297, 'long' => 21.0122],
        ['label' => 'Unione Europea', 'aliases' => ['european union', 'unione europea', 'bruxelles', 'brussels', 'europa'], 'lat' => 50.8503, 'long' => 4.3517],
        ['label' => 'Mediterraneo', 'aliases' => ['mediterranean', 'mediterraneo'], 'lat' => 35.0, 'long' => 18.0],
        ['label' => 'Sahel', 'aliases' => ['sahel'], 'lat' => 17.5707, 'long' => 3.9962],
        ['label' => 'Sudan', 'aliases' => ['sudan', 'khartoum'], 'lat' => 15.5007, 'long' => 32.5599],
        ['label' => 'Etiopia', 'aliases' => ['ethiopia', 'etiopia', 'addis ababa'], 'lat' => 9.032, 'long' => 38.7469],
        ['label' => 'Nigeria', 'aliases' => ['nigeria', 'lagos', 'abuja'], 'lat' => 9.0765, 'long' => 7.3986],
        ['label' => 'Africa Subsahariana', 'aliases' => ['africa subsahariana', 'sub saharan africa', 'africa'], 'lat' => 9.082, 'long' => 8.6753],
        ['label' => 'Libia', 'aliases' => ['libya', 'libia', 'tripoli'], 'lat' => 32.8872, 'long' => 13.1913],
        ['label' => 'Algeria', 'aliases' => ['algeria', 'algeri'], 'lat' => 36.7538, 'long' => 3.0588],
        ['label' => 'Egitto', 'aliases' => ['egypt', 'egitto', 'cairo', 'il cairo'], 'lat' => 30.0444, 'long' => 31.2357],
        ['label' => 'Siria', 'aliases' => ['syria', 'siria', 'damascus', 'damasco'], 'lat' => 33.5138, 'long' => 36.2765],
        ['label' => 'Iraq', 'aliases' => ['iraq', 'baghdad', 'bagdad'], 'lat' => 33.3152, 'long' => 44.3661],
        ['label' => 'Afghanistan', 'aliases' => ['afghanistan', 'kabul'], 'lat' => 34.5553, 'long' => 69.2075],
        ['label' => 'Pakistan', 'aliases' => ['pakistan', 'islamabad'], 'lat' => 33.6844, 'long' => 73.0479],
        ['label' => 'India', 'aliases' => ['india', 'new delhi', 'nuova delhi'], 'lat' => 28.6139, 'long' => 77.209],
        ['label' => 'Giappone', 'aliases' => ['japan', 'giappone', 'tokyo', 'tokio'], 'lat' => 35.6762, 'long' => 139.6503],
        ['label' => 'Corea del Nord', 'aliases' => ['north korea', 'corea del nord', 'pyongyang'], 'lat' => 39.0392, 'long' => 125.7625],
        ['label' => 'Corea del Sud', 'aliases' => ['south korea', 'corea del sud', 'seoul', 'seul'], 'lat' => 37.5665, 'long' => 126.978],
        ['label' => 'Taiwan', 'aliases' => ['taiwan', 'taipei'], 'lat' => 25.033, 'long' => 121.5654],
        ['label' => 'Cina', 'aliases' => ['china', 'cina', 'beijing', 'pechino'], 'lat' => 39.9042, 'long' => 116.4074],
        ['label' => 'Hong Kong', 'aliases' => ['hong kong'], 'lat' => 22.3193, 'long' => 114.1694],
        ['label' => 'Ucraina', 'aliases' => ['ukraine', 'ucraina', 'kyiv', 'kiev'], 'lat' => 50.4501, 'long' => 30.5234],
        ['label' => 'Bielorussia', 'aliases' => ['belarus', 'bielorussia', 'minsk'], 'lat' => 53.9006, 'long' => 27.559],
        ['label' => 'Russia', 'aliases' => ['russia', 'russian federation', 'moscow', 'mosca'], 'lat' => 55.7558, 'long' => 37.6173],
        ['label' => 'Israele', 'aliases' => ['israel', 'israele', 'jerusalem', 'gerusalemme', 'tel aviv'], 'lat' => 31.7683, 'long' => 35.2137],
        ['label' => 'Palestina', 'aliases' => ['palestine', 'palestina', 'west bank', 'cisgiordania'], 'lat' => 31.95, 'long' => 35.2],
        ['label' => 'Gaza', 'aliases' => ['gaza'], 'lat' => 31.5017, 'long' => 34.4668],
        ['label' => 'Libano', 'aliases' => ['lebanon', 'libano', 'beirut', 'beirut'], 'lat' => 33.8938, 'long' => 35.5018],
        ['label' => 'Iran', 'aliases' => ['iran', 'tehran', 'teheran'], 'lat' => 35.6892, 'long' => 51.389],
        ['label' => 'Arabia Saudita', 'aliases' => ['saudi arabia', 'arabia saudita', 'riyadh', 'riyad'], 'lat' => 24.7136, 'long' => 46.6753],
        ['label' => 'Yemen', 'aliases' => ['yemen', 'yemen', 'sanaa', 'sana'], 'lat' => 15.3694, 'long' => 44.191],
        ['label' => 'Turchia', 'aliases' => ['turkey', 'turchia', 'turca', 'turco', 'turchese', 'ankara', 'istanbul'], 'lat' => 39.9334, 'long' => 32.8597],
        ['label' => 'Armenia', 'aliases' => ['armenia', 'armenia', 'yerevan'], 'lat' => 40.1792, 'long' => 44.4991],
        ['label' => 'Azerbaigian', 'aliases' => ['azerbaijan', 'azerbaigian', 'baku'], 'lat' => 40.4093, 'long' => 49.8671],
        ['label' => 'Georgia', 'aliases' => ['georgia', 'georgia', 'tbilisi'], 'lat' => 41.7151, 'long' => 44.8271],
        ['label' => 'Venezuela', 'aliases' => ['venezuela', 'caracas'], 'lat' => 10.4806, 'long' => -66.9036],
        ['label' => 'Cuba', 'aliases' => ['cuba', 'havana', 'l avana'], 'lat' => 23.1136, 'long' => -82.3666],
        ['label' => 'Messico', 'aliases' => ['mexico', 'messico', 'mexico city'], 'lat' => 19.4326, 'long' => -99.1332],
        ['label' => 'Brasile', 'aliases' => ['brazil', 'brasile', 'brasilia'], 'lat' => -15.7939, 'long' => -47.8828],
        ['label' => 'Argentina', 'aliases' => ['argentina', 'buenos aires'], 'lat' => -34.6037, 'long' => -58.3816],
        ['label' => 'NATO', 'aliases' => ['nato', 'atlantic'], 'lat' => 50.8503, 'long' => 4.3517],
        ['label' => 'Asia', 'aliases' => ['asia'], 'lat' => 34.0479, 'long' => 100.6197],
    ],

    'generic_region_patterns' => [
        'area non specificata',
        'non specificata',
        'non specificato',
        'globale',
        'global',
        'worldwide',
        'mondiale',
        'internazionale generale',
        'unknown region',
        'regione sconosciuta',
    ],
];
